apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # imagePullSecrets:
      # - name: myregistrykey
      containers:
      - name: my-app
        image: 127.0.0.1.nip.io/nodejs_ritter:TAG_NAME
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
---
  apiVersion: v1
  kind: Service	
  metadata:
    name: my-app
    labels:
      app: my-app
  spec:
    selector:
      app: my-app
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
